language: shell
os:
  - linux
  - osx
  - windows
env:
  - STACK_ROOT=$HOME/.stack
cache:
  directories:
    - $STACK_ROOT
    - .stack-work
    - $HOME/AppData/Local/Programs/stack
install:
  - curl --location https://get.haskellstack.org | sh
script:
  - stack build --haddock --test
  - stack sdist
after_success:
  - mv -v "$( stack path --local-doc-root )"/aural-* gh-pages
  - cp -v "$( stack exec which aural )" "aural-$TRAVIS_OS_NAME-$TRAVIS_BRANCH"
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: gh-pages
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file: aural-$TRAVIS_OS_NAME-$TRAVIS_BRANCH
    on:
      tags: true
