language: shell
os:
  - linux
  - osx
  - windows
env:
  - STACK_ROOT=$HOME/.stack
cache:
  directories:
    - $STACK_ROOT
    - .stack-work
    - $HOME/AppData/Local/Programs/stack
install:
  - curl --location https://get.haskellstack.org | sh
  - stack --version
script:
  - stack build --copy-bins --haddock --test
  - stack sdist
after_success:
  - test -n "$TRAVIS_TAG" && mv -v "$( stack path --local-doc-root )/aural-$TRAVIS_TAG" "aural-$TRAVIS_TAG-haddock"
  - test -n "$TRAVIS_TAG" && cp -v "$( stack exec which aural )" "aural-$TRAVIS_TAG-$TRAVIS_OS_NAME"
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: aural-$TRAVIS_TAG-haddock
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: aural-$TRAVIS_TAG-$TRAVIS_OS_NAME*
    on:
      tags: true
