language: shell
os:
  - linux
  - osx
  - windows
cache:
  directories:
    - $HOME/.stack
    - .stack-work
install:
  - curl --location https://get.haskellstack.org | sh
  - stack setup
script:
  - stack test
  - stack sdist
